<a href="https://colab.research.google.com/github/thanhle3968/optimal_theory_pair_trading/blob/main/prepair_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install vnstock
!pip install ta

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting vnstock
  Downloading vnstock-0.1.4-py3-none-any.whl (17 kB)
Installing collected packages: vnstock
Successfully installed vnstock-0.1.4
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ta
  Downloading ta-0.10.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from ta) (1.22.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from ta) (1.5.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->ta) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->ta) (1.16.0)
Building wheels for collected packages: ta
  Building wheel for ta (setup.py) ... done
  Created wheel for ta: filename=ta-0.10.2-py3-none-any.whl size=29103 sha256=6339c156f3e356f83935037fa36b491666035afed1b8b3f4c8072e68a031b707
  Stored in directory: /root/.cache/pip/wheels/47/51/06/380dc516ea78621870b93ff65527c251afdfdc5fa9d7f4d248
Successfully built ta
Installing collected packages: ta
Successfully installed ta-0.10.2

In [ ]:
from vnstock import *
from ta.volume import on_balance_volume
from ta.momentum import rsi
from ta.volatility import bollinger_mavg, bollinger_lband, bollinger_hband
from ta.trend import ema_indicator

In [ ]:
stock_name = 'TCB'
start_date = '2019-01-01'
end_date = '2024-05-01'

df =  stock_historical_data(symbol=stock_name, 
                            start_date=start_date, 
                            end_date=end_date)
df = df.set_index('TradingDate')
print(df.tail())

                Open     High      Low    Close   Volume
TradingDate
2023-04-27   30200.0  30200.0  29850.0  29900.0  2032454
2023-04-28   29950.0  29950.0  29500.0  29500.0  2478528
2023-05-04   29500.0  29500.0  28900.0  29050.0  1918703
2023-05-05   29050.0  29200.0  28450.0  28700.0  3438755
2023-05-08   28900.0  29400.0  28700.0  29400.0  2847866

In [ ]:
df['close_open_diff'] = df['Close'] - df['Open']
df['high_close_diff'] = df['High'] - df['Close']
df['low_close_diff'] = df['Low'] - df['Close']
df['high_open_diff'] = df['High'] - df['Open']
df['low_open_diff'] = df['Low'] - df['Open']
df['high_low_diff'] = df['High'] - df['Low']

df['close_p1'] = df['Close'].shift(1)
df['close_p2'] = df['Close'].shift(2)
df['close_p3'] = df['Close'].shift(3)
df['close_p7'] = df['Close'].shift(7)

df['close_diff_p1'] = df['Close'].diff(1)
df['close_diff_p2'] = df['Close'].diff(2)
df['close_diff_p3'] = df['Close'].diff(3)
df['close_diff_p7'] = df['Close'].diff(7)

df['close_diff_pct_p1'] = df['Close'].pct_change(1)
df['close_diff_pct_p2'] = df['Close'].pct_change(2)
df['close_diff_pct_p3'] = df['Close'].pct_change(3)
df['close_diff_pct_p7'] = df['Close'].pct_change(7)

df['volume_p1'] = df['Volume'].shift(1)
df['volume_p2'] = df['Volume'].shift(2)
df['volume_p3'] = df['Volume'].shift(3)
df['volume_p7'] = df['Volume'].shift(7)

df['volume_diff_p1'] = df['Volume'].diff(1)
df['volume_diff_p2'] = df['Volume'].diff(2)
df['volume_diff_p3'] = df['Volume'].diff(3)
df['volume_diff_p7'] = df['Volume'].diff(7)

df['volume_diff_pct_p1'] = df['Volume'].pct_change(1)
df['volume_diff_pct_p2'] = df['Volume'].pct_change(2)
df['volume_diff_pct_p3'] = df['Volume'].pct_change(3)
df['volume_diff_pct_p7'] = df['Volume'].pct_change(7)

df['on_balance_volume'] = on_balance_volume(df['Close'], df['Volume'])

df['rsi_window_14'] = rsi(df['Close'])
df['rsi_window_7'] = rsi(df['Close'], 7)

df['bollinger_mavg_20'] = bollinger_mavg(df['Close'])
df['bollinger_lband_20'] = bollinger_lband(df['Close'])
df['bollinger_hband_20'] = bollinger_hband(df['Close'])

df['ema_12'] = ema_indicator(df['Close'])
df['ema_26'] = ema_indicator(df['Close'], 26)

In [ ]:
df = df.dropna()

In [ ]:
#
df['close_t1'] = df['Close'].shift(-1)
df['close_t2'] = df['Close'].shift(-2)
df['close_t3'] = df['Close'].shift(-3)

df['open_t1'] = df['Open'].shift(-1)
df['open_t2'] = df['Open'].shift(-2)
df['open_t3'] = df['Open'].shift(-3)

<ipython-input-6-6685185edc41>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['close_t1'] = df['Close'].shift(-1)
<ipython-input-6-6685185edc41>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['close_t2'] = df['Close'].shift(-2)
<ipython-input-6-6685185edc41>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['close_t3'] = df['Close'].shift(-3)
<ipython-input-6-6685185edc41>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['open_t1'] = df['Open'].shift(-1)
<ipython-input-6-6685185edc41>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['open_t2'] = df['Open'].shift(-2)
<ipython-input-6-6685185edc41>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['open_t3'] = df['Open'].shift(-3)

In [ ]:
df

,Open,High,Low,Close,Volume,close_open_diff,high_close_diff,low_close_diff,high_open_diff,low_open_diff,...,bollinger_lband_20,bollinger_hband_20,ema_12,ema_26,close_t1,close_t2,close_t3,open_t1,open_t2,open_t3
TradingDate,,,,,,,,,,,,,,,,,,,,,
2019-02-13,27450.0,27750.0,27400.0,27550.0,2519920,100.0,200.0,-150.0,300.0,-50.0,...,25698.711702,27616.288298,26895.629781,26517.384182,27300.0,27250.0,27350.0,27500.0,27200.0,27300.0
2019-02-14,27500.0,27600.0,27250.0,27300.0,2290940,-200.0,300.0,-50.0,100.0,-250.0,...,25820.208928,27644.791072,26957.840584,26575.355724,27250.0,27350.0,27550.0,27200.0,27300.0,27400.0
2019-02-15,27200.0,27650.0,27100.0,27250.0,3355310,50.0,400.0,-150.0,450.0,-100.0,...,25921.558531,27668.441469,27002.788186,26625.329374,27350.0,27550.0,27550.0,27300.0,27400.0,27650.0
2019-02-18,27300.0,27550.0,27250.0,27350.0,2160450,50.0,200.0,-100.0,250.0,-50.0,...,26080.443162,27659.556838,27056.205388,26679.008680,27550.0,27550.0,27500.0,27400.0,27650.0,27600.0
2019-02-19,27400.0,28200.0,27400.0,27550.0,7850600,150.0,650.0,-150.0,800.0,0.0,...,26099.411305,27745.588695,27132.173790,26743.526555,27550.0,27500.0,27700.0,27650.0,27600.0,27500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-27,30200.0,30200.0,29850.0,29900.0,2032454,-300.0,300.0,-50.0,0.0,-350.0,...,28299.276536,30675.723464,29384.351618,28957.793448,29500.0,29050.0,28700.0,29950.0,29500.0,29050.0
2023-04-28,29950.0,29950.0,29500.0,29500.0,2478528,-450.0,450.0,0.0,0.0,-450.0,...,28477.339005,30612.660995,29402.143677,28997.956896,29050.0,28700.0,29400.0,29500.0,29050.0,28900.0
2023-05-04,29500.0,29500.0,28900.0,29050.0,1918703,-450.0,450.0,-150.0,0.0,-600.0,...,28447.937876,30617.062124,29347.967727,29001.811941,28700.0,29400.0,NaN,29050.0,28900.0,NaN
2023-05-05,29050.0,29200.0,28450.0,28700.0,3438755,-350.0,500.0,-250.0,150.0,-600.0,...,28348.701504,30636.298496,29248.280384,28979.455501,29400.0,NaN,NaN,28900.0,NaN,NaN
2023-05-08,28900.0,29400.0,28700.0,29400.0,2847866,500.0,0.0,-700.0,500.0,-200.0,...,28343.002294,30631.997706,29271.621863,29010.606945,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.to_csv("/content/drive/MyDrive/VU DUC HOA/project/trading ml cource /data/tcb_data_feature.csv", index=True)